name = "BZpaths"
uuid = "f8cfb5e1-ca40-4b8f-9b88-500575390b6d"
authors = ["Fernando Pe√±aranda"]
version = "1.0.0-DEV"

[deps]
Bravais = "ada6cbde-b013-4edf-aa94-f6abe8bd6e6b"
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
